services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-playground
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight Web UI
    environment:
      - REDIS_ARGS=--appendonly yes
    volumes:
      - redis_data:/data
      - ./scripts:/scripts
      - ./sample-data:/sample-data
    command: redis-stack-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
